"""add trade_no

Revision ID: 9b437f67b3b5
Revises: 137b0fe2b99c
Create Date: 2019-05-21 14:16:48.027686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b437f67b3b5'
down_revision = '137b0fe2b99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ks_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ks_order_info', 'trade_no')
    # ### end Alembic commands ###
